const COLOUR_RED              = 'cc0000';
const COLOUR_WHITE            = 'ffffff';
const COLOUR_PURPLE           = 'ac00e6';
const COLOUR_GREEN            = '66cc00';
const COLOUR_BLUE             = '66b3ff';
const COLOUR_DARK_GREEN       = '00cc99';
const COLOUR_ORANGE           = 'e6b800';
const COLOUR_YELLOW           = 'FFFF00';
const COLOUR_BLACK            = '000000';

const GENSHIN_ELEMENT_PYRO    = 'ELEMENT_PYRO';
const GENSHIN_ELEMENT_CRYO    = 'ELEMENT_CRYO';
const GENSHIN_ELEMENT_ELECTRO = 'ELEMENT_ELECTRO';
const GENSHIN_ELEMENT_DENDRO  = 'ELEMENT_DENDRO';
const GENSHIN_ELEMENT_HYDRO   = 'ELEMENT_HYDRO';
const GENSHIN_ELEMENT_ANEMO   = 'ELEMENT_ANEMO';
const GENSHIN_ELEMENT_GEO     = 'ELEMENT_GEO';

module.exports = {
    COLOUR_RED,
    COLOUR_WHITE,
    COLOUR_PURPLE,
    COLOUR_GREEN,
    COLOUR_BLUE,
    COLOUR_DARK_GREEN,
    COLOUR_ORANGE,
    COLOUR_YELLOW,
    COLOUR_BLACK,
    GENSHIN_ELEMENT_PYRO,
    GENSHIN_ELEMENT_CRYO,
    GENSHIN_ELEMENT_ELECTRO,
    GENSHIN_ELEMENT_DENDRO,
    GENSHIN_ELEMENT_HYDRO,
    GENSHIN_ELEMENT_ANEMO,
    GENSHIN_ELEMENT_GEO,
  };