DROP SCHEMA IF EXISTS DiscordBotDB;
CREATE DATABASE DiscordBotDB;
USE DiscordBotDB;

CREATE TABLE Guild (
	guildId VARCHAR(100) NOT NULL PRIMARY KEY,
	guildOwnerId VARCHAR(100) NOT NULL
);

CREATE TABLE GuildConfigurable(
	guildId VARCHAR(100) NOT NULL PRIMARY KEY,
	cmdPrefix VARCHAR(10) DEFAULT 'ivooo',
	modLogId VARCHAR(100)
);

CREATE TABLE Playlist (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	guildId VARCHAR(100) NOT NULL,
	FOREIGN KEY (guildId) REFERENCES Guild(guildId),
	CONSTRAINT UN_Playlist UNIQUE (name, guildId)
);

CREATE TABLE Song (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	songTitle VARCHAR(100) NOT NULL,
	artist VARCHAR(100) NOT NULL,
	CONSTRAINT UN_Song UNIQUE (songTitle, artist)
);

CREATE TABLE Playlist_Songs (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	playlistId INT NOT NULL,
	songId INT NOT NULL,
	FOREIGN KEY (playlistId) REFERENCES Playlist(id),
	FOREIGN KEY (songId) REFERENCES Song(id),
	CONSTRAINT UN_PlaylistSongs UNIQUE (playlistId, songId)
);